plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
title: MartinRL.github.io
description: Servant Leader, Senior (Director/VP/Head of) Engineering Manager, Software Architect (who can code), Father, Husband, Friend, Ultracyclist.
theme: jekyll-theme-minimal
