plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
title: MartinRL.github.io
description: Manager, Software Developer/Architect, Father, Husband, Cyclist.
theme: jekyll-theme-minimal
